# automatically generated by the FlatBuffers compiler, do not modify

# namespace: TransCity

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DenyReason(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DenyReason()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDenyReason(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DenyReasonBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x4E\x59\x53", size_prefixed=size_prefixed)

    # DenyReason
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DenyReason
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DenyReason
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DenyReasonStart(builder):
    builder.StartObject(2)

def Start(builder):
    DenyReasonStart(builder)

def DenyReasonAddId(builder, id):
    builder.PrependUint8Slot(0, id, 0)

def AddId(builder, id):
    DenyReasonAddId(builder, id)

def DenyReasonAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    DenyReasonAddValue(builder, value)

def DenyReasonEnd(builder):
    return builder.EndObject()

def End(builder):
    return DenyReasonEnd(builder)
